apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: demo-secret
  namespace: default
spec:
  provider: azure
  secretObjects:
  - secretName: demosecret
    type: Opaque
    data:
    - objectName: "SPRING-DATASOURCE-URL"
      key: SPRING-DATASOURCE-URL
    - objectName: "SPRING-DATASOURCE-USERNAME"
      key: SPRING-DATASOURCE-USERNAME
    - objectName: "SPRING-DATASOURCE-PASSWORD"
      key: SPRING-DATASOURCE-PASSWORD
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "d7dfd620-a1cf-4acd-b0ef-e081530d5f60"
    keyvaultName: "Key-Vault-Integration"
    objects: |
      array:
        - |
          objectName: "SPRING-DATASOURCE-URL"
          objectType: secret
        - |
          objectName: "SPRING-DATASOURCE-USERNAME"
          objectType: secret
        - |
          objectName: "SPRING-DATASOURCE-PASSWORD"
          objectType: secret
    tenantId: "ccf7f24b-d025-4dc0-b06b-2f93f5418212"
