apiVersion: v1
kind: Service
metadata:
  name: backend-svc
spec:
  ports:
    - name: "8089"
      port: 8089
      targetPort: 8089
  selector:
    component: web-backend
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
spec:
  type: LoadBalancer
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    component: web-frontend
